swagger: "2.0"

info:
  title: TableClassifier Server
  version: "0.0.1"

paths:
  /classify:
    post:
      summary: Classify a JSON hash of data
      description: Generate a JSON response with a single key 'label'
      operationId: tableclassifier.server.classify
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: classification response
          schema:
            type: object
          examples:
            "application/json": "{'label': 'spam', 'score': 0.7}"
      parameters:
        - name: dict_from_json
          description: a row of data to classify, supplied as name/value pairs in JSON
          in: body
          required: true
          schema:
            type: object